### ISSUE TITLE
Learning gobot

### ISSUE THREAD

**Issue by omgnuts** [cpalone/gobot#2]
Hello, I'm kind of new to golang, and I'm trying to play with gobot. I managed to get the dependencies sorted out, the program seems to be running. I don't know if I'm doing this right, but I tried to configure main with:

```
b.Rooms["public"].Handlers = []gobot.Handler{&handlers.PongHandler{}}
```

and I changed sample.yml to 

```
Bot:
    Name: GoBotSample
    DbPath: GoBotSample.db
Rooms:
-
    RoomName: public
```

But I dont really see my bot in the public room at euphoria.io. How should I configure the sample gobot so it appears in the room and replies to ping with pong? :)

**Comment by omgnuts** [comment]
Hi again, ok an update. Finally got the bot working that plays !ping,pong! cool :)

Another question tho, what does GoBotSample.db do?

**Comment by ckingdev** [comment]
Hey! I'm thrilled that you're using gobot to play around with Go. It's a great language, and I think gobot shows some of its strengths well. What was the first problem you were having? I'll do my best to clarify in documentation.

As for the database- that's a bolt db (https://github.com/boltdb/bolt) that can optionally be used by writing new Handlers for gobot. With the base package, nothing uses the database. It's just there for easy extension. Keep in mind that the database is per bot, not per room.

Please let me know if you have any more questions! If email is easier for you, you can reach me at cam@cpalone.me. Thanks for checking out my library :)

**Comment by omgnuts** [comment]
Hey!!! Sorry i just saw this email. The bot is working great now. Im still
very new to go but perhaps i could help you out in some documentation from
a super newbie perspective.

Ill check out bolt db. Im not sure how this works but im adding more
handlers in roomconfig.addlhandlers. but dont worry Ill try to figure the
whole flow first.

Meanwhile, im modifying some code to get practice. Will definitely ask you
for more help :D Thanks for sharing ur code, really helps a newbie like me
to learn go faster.

PS: are u nihizg at euphoria??

**Comment by ckingdev** [comment]
Nope! I'm skow- I'm a consultant for euphoria. What's your username?

Closing just for bookkeeping :)

**Comment by omgnuts** [comment]
okk cool, im peanuts & peabot's my bot :)

**Comment by omgnuts** [comment]
Hey Cam! Just a quick update. I played around with gobot a bit, and its
really neatly designed. I learnt a lot from your code :D tks! So I fiddled
around and implemented a simple handler to respond to small chatbotting.
Its kinda crude, but if you want i could clean it up and push the code
upstream these few days.

**Comment by ckingdev** [comment]
Thanks! I'm really glad it's helpful! I'm not so sure about incorporating that functionality into the main library, but I would love to have you contribute! How would you feel about implementing a handler? I have a few small things I'd like to add but haven't had the time- I could make a list for you. Let me know!

**Comment by omgnuts** [comment]
Sure! I'd be glad to try out more coding in go. What handlers do you need?

**Comment by ckingdev** [comment]
We could really use functionality that acts as leaving a message for someone. 

Example:

User A wants to tell User B something.
User A sends a message to the room "!tell @UserB this is an important message"
The bot records this message and its recipient.
User B comes into the room later, and says something.
The bot replies to that message with "from @UserA: this is an important message"

Interested?

**Comment by omgnuts** [comment]
Hey Cam, sorry was busy last few days- sure i could have a look at that.

**Comment by omgnuts** [comment]
Hi Cam, you can test the notify bot in the test room.

The command is !tell username message. Then switch to the receipent and
type something. You should see the notifications.

**Comment by omgnuts** [comment]
Hi Cam, do you still want the module?
